"""
dbt schema.yml generator (Snowflake)
====================================
Introspects a Snowflake table and emits a dbt `version: 2` schema YAML with
`data_tests:` per column. Behavior:

  1. Build the YAML for the table.
  2. If a file <model>.yml already exists in the output dir -> do NOT overwrite.
  3. Otherwise create it.
  4. Always print the YAML to stdout (the "return as a string" part).

Constraint mapping (Snowflake enforces only NOT NULL; the rest are data-quality
tests, which is exactly what dbt generic tests are):
    NOT NULL                 -> not_null
    single-col PK / UNIQUE   -> unique
    composite PK             -> model-level  unique_multi_column
    FOREIGN KEY              -> relationships (to: ref(parent), field: col)

Usage:
    python gen_dbt_yaml.py --table DATAWAREHOUSE_PROD.MART.FOURNISSEUR \
        --account abc123.us-east-1 --user JDOE --warehouse WH --role ANALYST \
        --out-dir models/mart

    # SSO instead of password:
    python gen_dbt_yaml.py --table MART.FOURNISSEUR --authenticator externalbrowser \
        --account abc123.us-east-1 --user JDOE --database DATAWAREHOUSE_PROD

Stdout is clean YAML; status messages go to stderr (so you can redirect/pipe).
"""

import argparse
import getpass
import os
import re
import sys


# ── Parsing (pure; takes DESCRIBE / SHOW rows as dicts) ───────────────────────

def _norm(rows):
    return [{k.lower(): v for k, v in r.items()} for r in rows]


def parse_columns(desc_rows):
    columns, composite_pk = [], []
    for d in _norm(desc_rows):
        name = d.get("name")
        is_pk = str(d.get("primary key", "N")).upper() == "Y"
        is_uq = str(d.get("unique key", "N")).upper() == "Y"
        nullable = str(d.get("null?", "Y")).upper() == "Y"
        if is_pk:
            composite_pk.append(name)
        columns.append({
            "name": name,
            "type": d.get("type") or "",
            "nullable": nullable,
            "default": d.get("default"),
            "primary_key": is_pk,
            "unique": is_uq,
            "foreign_key": None,
        })
    return columns, composite_pk


def parse_fks(fk_rows):
    fkmap = {}
    for d in _norm(fk_rows):
        fkcol = d.get("fk_column_name")
        if fkcol:
            parent = ".".join(p for p in (
                d.get("pk_database_name"),
                d.get("pk_schema_name"),
                d.get("pk_table_name"),
            ) if p)
            fkmap[fkcol] = "%s.%s" % (parent, d.get("pk_column_name"))
    return fkmap


# ── YAML builder (pure; hand-rolled to control dbt structure exactly) ──────────

def build_dbt_yaml(model_name, columns, composite_pk):
    L = ["# Generated by gen_dbt_yaml.py -- review ref()/source() targets and",
         "# the unique_multi_column arg name to match your project's custom test.",
         "version: 2",
         "",
         "models:",
         "  - name: %s" % model_name.lower()]

    # Composite PK -> model-level multi-column uniqueness test.
    if len(composite_pk) > 1:
        L.append("    data_tests:")
        L.append("      - unique_multi_column:")
        L.append("          combination_of_columns:")
        for c in composite_pk:
            L.append("            - %s" % c.lower())

    L.append("    columns:")
    for col in columns:
        name = col["name"].lower()
        tests = []
        if not col["nullable"]:
            tests.append("not_null")
        single_pk = col["primary_key"] and len(composite_pk) <= 1
        if single_pk or (col["unique"] and not col["primary_key"]):
            tests.append("unique")

        L.append("      - name: %s" % name)
        rel = col["foreign_key"]
        if tests or rel:
            L.append("        data_tests:")
            for t in tests:
                L.append("          - %s" % t)
            if rel:
                parts = rel.split(".")
                parent_table = parts[-2] if len(parts) >= 2 else parts[0]
                parent_col = parts[-1]
                L.append("          - relationships:")
                L.append("              to: ref('%s')" % parent_table.lower())
                L.append("              field: %s" % parent_col.lower())

    return "\n".join(L) + "\n"


# ── File handling ─────────────────────────────────────────────────────────────

def write_if_absent(path, content):
    """Returns True if it created the file, False if it already existed."""
    if os.path.exists(path):
        return False
    d = os.path.dirname(path)
    if d:
        os.makedirs(d, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return True


# ── Snowflake connection + introspection ──────────────────────────────────────

def connect(args):
    import snowflake.connector
    params = {
        "account": args.account, "user": args.user, "database": args.database,
        "schema": args.schema, "warehouse": args.warehouse, "role": args.role,
    }
    params = {k: v for k, v in params.items() if v}
    if args.authenticator:
        params["authenticator"] = args.authenticator
        if args.authenticator.lower() not in ("externalbrowser", "oauth"):
            params["password"] = os.environ.get("SNOWFLAKE_PASSWORD") or getpass.getpass("Snowflake password: ")
    else:
        params["password"] = os.environ.get("SNOWFLAKE_PASSWORD") or getpass.getpass("Snowflake password: ")
    return snowflake.connector.connect(**params)


def introspect(conn, table_name):
    from snowflake.connector import DictCursor
    cur = conn.cursor(DictCursor)
    cur.execute("DESCRIBE TABLE " + table_name)
    columns, composite_pk = parse_columns(cur.fetchall())
    try:
        cur.execute("SHOW IMPORTED KEYS IN TABLE " + table_name)
        fkmap = parse_fks(cur.fetchall())
        for c in columns:
            if c["name"] in fkmap:
                c["foreign_key"] = fkmap[c["name"]]
    except Exception:
        pass  # no FKs or insufficient privileges
    return columns, composite_pk


# ── Entry point ───────────────────────────────────────────────────────────────

def main():
    p = argparse.ArgumentParser(description="Generate a dbt schema.yml from a Snowflake table.")
    p.add_argument("--table", required=True, help="TABLE, SCHEMA.TABLE, or DB.SCHEMA.TABLE")
    p.add_argument("--out-dir", default=".", help="Directory for <model>.yml (default: cwd)")
    p.add_argument("--account"); p.add_argument("--user"); p.add_argument("--database")
    p.add_argument("--schema"); p.add_argument("--warehouse"); p.add_argument("--role")
    p.add_argument("--authenticator", help="e.g. 'externalbrowser' for SSO")
    args = p.parse_args()

    if not re.match(r'^[A-Za-z0-9_$. "]+$', args.table):
        sys.exit("Invalid table name: %r" % args.table)

    model = args.table.split(".")[-1].strip('"')

    conn = connect(args)
    try:
        columns, composite_pk = introspect(conn, args.table)
    finally:
        conn.close()

    yaml_text = build_dbt_yaml(model, columns, composite_pk)
    path = os.path.join(args.out_dir, model.lower() + ".yml")

    if write_if_absent(path, yaml_text):
        print("[created] %s" % path, file=sys.stderr)
    else:
        print("[exists]  %s (not overwriting)" % path, file=sys.stderr)

    sys.stdout.write(yaml_text)


if __name__ == "__main__":
    main()
